export const MAP_OF_VISUAL_ZONE_COLORS_TO_CSS_CLASSES: Record<string, VisualStyleForZoneColor> = {
    purple: { 
        borderClassName: 'border-purple-500', 
        shadowClassName: 'shadow-none', 
        handleBackgroundClassName: '!bg-purple-500',
        backgroundClassName: 'bg-purple-500',
        iconBackgroundClassName: "bg-zinc-900 text-purple-400 dark:bg-zinc-800 dark:text-purple-400",
        borderSelectedClassName: "!border-purple-500",
        textClassName: 'text-purple-400',
        resizerLineClassName: 'border-purple-500',
        resizerHandleClassName: 'border-purple-500',
        hoverBackgroundClassName: 'bg-purple-500',
        level1HoverBackgroundClassName: 'hover:bg-purple-500',
        labelBorderClassName: 'border-purple-500',
    },
    blue: { 
        borderClassName: 'border-blue-500', 
        shadowClassName: 'shadow-none', 
        handleBackgroundClassName: '!bg-blue-500',
        backgroundClassName: 'bg-blue-500',
        iconBackgroundClassName: "bg-zinc-900 text-blue-400 dark:bg-zinc-800 dark:text-blue-400",
        borderSelectedClassName: "!border-blue-500",
        textClassName: 'text-blue-400',
        resizerLineClassName: 'border-blue-500',
        resizerHandleClassName: 'border-blue-500',
        hoverBackgroundClassName: 'bg-blue-500',
        level1HoverBackgroundClassName: 'hover:bg-blue-500',
        activeOutputClassName: "!bg-blue-500 !border-blue-400",
        labelBorderClassName: 'border-blue-500',
    },
    pink: { 
        borderClassName: 'border-pink-500', 
        shadowClassName: 'shadow-none', 
        handleBackgroundClassName: '!bg-pink-500',
        backgroundClassName: 'bg-pink-500',
        iconBackgroundClassName: "bg-zinc-900 text-pink-400 dark:bg-zinc-800 dark:text-pink-400",
        borderSelectedClassName: "!border-pink-500",
        textClassName: 'text-pink-400',
        resizerLineClassName: 'border-pink-500',
        resizerHandleClassName: 'border-pink-500',
        hoverBackgroundClassName: 'bg-pink-500',
        level1HoverBackgroundClassName: 'hover:bg-pink-500',
        activeOutputClassName: "!bg-pink-500 !border-pink-400",
        labelBorderClassName: 'border-pink-500',
    },
    green: { 
        borderClassName: 'border-green-500', 
        shadowClassName: 'shadow-none', 
        handleBackgroundClassName: '!bg-green-500',
        backgroundClassName: 'bg-green-500',
        iconBackgroundClassName: "bg-zinc-900 text-green-400 dark:bg-zinc-800 dark:text-green-400",
        borderSelectedClassName: "!border-green-500",
        textClassName: 'text-green-400',
        resizerLineClassName: 'border-green-500',
        resizerHandleClassName: 'border-green-500',
        hoverBackgroundClassName: 'bg-green-500',
        level1HoverBackgroundClassName: 'hover:bg-green-500',
        activeOutputClassName: "!bg-green-500 !border-green-400",
        labelBorderClassName: 'border-green-500',
    },
    yellow: { 
        borderClassName: 'border-yellow-500', 
        shadowClassName: 'shadow-none', 
        handleBackgroundClassName: '!bg-yellow-500',
        backgroundClassName: 'bg-yellow-500',
        iconBackgroundClassName: "bg-zinc-900 text-yellow-400 dark:bg-zinc-800 dark:text-yellow-400",
        borderSelectedClassName: "!border-yellow-500",
        textClassName: 'text-yellow-400',
        resizerLineClassName: 'border-yellow-500',
        resizerHandleClassName: 'border-yellow-500',
        hoverBackgroundClassName: 'bg-yellow-500',
        level1HoverBackgroundClassName: 'hover:bg-yellow-500',
        activeOutputClassName: "!bg-yellow-500 !border-yellow-400",
        labelBorderClassName: 'border-yellow-500',
    },
    orange: { 
        borderClassName: 'border-orange-500', 
        shadowClassName: 'shadow-none', 
        handleBackgroundClassName: '!bg-orange-500',
        backgroundClassName: 'bg-orange-500',
        iconBackgroundClassName: "bg-zinc-900 text-orange-400 dark:bg-zinc-800 dark:text-orange-400",
        borderSelectedClassName: "!border-orange-500",
        textClassName: 'text-orange-400',
        resizerLineClassName: 'border-orange-500',
        resizerHandleClassName: 'border-orange-500',
        hoverBackgroundClassName: 'bg-orange-500',
        level1HoverBackgroundClassName: 'hover:bg-orange-500',
        activeOutputClassName: "!bg-orange-500 !border-orange-400",
        labelBorderClassName: 'border-orange-500',
    },
    default: {
        borderClassName: 'border-zinc-700',
        shadowClassName: 'shadow-none',
        handleBackgroundClassName: '!bg-zinc-500',
        backgroundClassName: 'bg-transparent',
        iconBackgroundClassName: "bg-zinc-900 text-zinc-400 dark:bg-zinc-800 dark:text-zinc-400",
        borderSelectedClassName: "!border-blue-600",
        textClassName: 'text-blue-400',
        resizerLineClassName: 'border-blue-500',
        resizerHandleClassName: 'border-blue-500',
        hoverBackgroundClassName: 'bg-zinc-800', 
        level1HoverBackgroundClassName: 'hover:bg-zinc-800',
        activeOutputClassName: "!bg-zinc-500",
        labelBorderClassName: 'border-zinc-700',
    }
};
