import { InboxBrowser } from "@/modules/inbox/features/review-inbox/ui/InboxBrowser";
import { getInboxItems } from "@/modules/inbox/features/review-inbox/infrastructure/api";
import { ModulePageLayout } from "@/shared/ui/layout/ModulePageLayout";
import { shouldShowPagination } from "@/shared/lib/pagination";

const InboxPage = async () => {
    const items = await getInboxItems();

    return (
        <ModulePageLayout
            title="Inbox"
            description="Review and approve content generated by your agents."
            breadcrumbs={[
                { label: "Home", href: "/home" },
                { label: "Inbox" }
            ]}
            pagination={null}
            showPagination={shouldShowPagination(items.length)}
        >
            <InboxBrowser initialItems={items} />
        </ModulePageLayout>
    );
};

export default InboxPage;