import { InboxList } from "@/modules/inbox/features/review-inbox/ui/InboxList";
import { getInboxItems } from "@/modules/inbox/features/review-inbox/infrastructure/api";
import { PageHeader } from "@/shared/ui/layout/PageHeader";
import { PageContainer } from "@/shared/ui/layout/PageContainer";
import { PageContent } from "@/shared/ui/layout/PageContent";

const InboxPage = async () => {
    const items = await getInboxItems();

    return (
        <PageContainer>
            <PageHeader 
                title="Inbox" 
                description="Review and approve content generated by your agents." 
            />
            <PageContent>
                <InboxList items={items} />
            </PageContent>
        </PageContainer>
    );
};

export default InboxPage;