'use server';

import { createStreamableUI } from 'ai/rsc';
import { ReactNode } from 'react';

// Mock Component for Generative UI
const WeatherCard = ({ location, temp }: { location: string; temp: string }) => (
  <div className="border p-4 rounded-lg bg-blue-50 text-blue-900 w-full max-w-sm my-2">
    <h3 className="font-bold text-lg">{location}</h3>
    <p className="text-3xl">{temp}°C</p>
    <p className="text-sm opacity-80">Generated by Axon AI</p>
  </div>
);

export async function submitUserMessage(input: string): Promise<{ id: number; display: ReactNode }> {
  const ui = createStreamableUI();

  // Simulate Backend Latency and Streaming
  (async () => {
    ui.update(
      <div className="flex items-center gap-2 text-muted-foreground text-sm my-2">
        <span className="animate-pulse">Thinking...</span>
      </div>
    );

    await new Promise(resolve => setTimeout(resolve, 800));

    // Simple Router logic to demonstrate Generative UI
    if (input.toLowerCase().includes('weather')) {
      ui.done(<WeatherCard location="Warsaw" temp="22" />);
    } else if (input.toLowerCase().includes('chart')) {
        ui.done(
            <div className="border p-4 rounded bg-gray-50 my-2">
                <p className="font-mono text-xs text-green-600">Generating Chart...</p>
                <div className="h-32 bg-gray-200 mt-2 rounded flex items-center justify-center text-gray-400">
                    [Chart Visualization]
                </div>
            </div>
        )
    } else {
      ui.done(
        <div className="bg-muted/20 p-3 rounded-lg text-sm my-2">
          {input} (Echo from Generative UI)
        </div>
      );
    }
  })();

  return {
    id: Date.now(),
    display: ui.value,
  };
}
