"""add_priority_chain_to_routers

Revision ID: 045969777155
Revises: 5d64a4c5542e
Create Date: 2026-03-28 20:17:43.414584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '045969777155'
down_revision: Union[str, Sequence[str], None] = '5d64a4c5542e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_routers', sa.Column('priority_chain', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('llm_routers', 'primary_model_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_routers', 'primary_model_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('llm_routers', 'priority_chain')
    # ### end Alembic commands ###
