"""add_canvas_data_to_spaces

Revision ID: 12506e5755be
Revises: 6208e2095021
Create Date: 2026-04-16 23:29:11.475015

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '12506e5755be'
down_revision: Union[str, Sequence[str], None] = '6208e2095021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('spaces', sa.Column('canvas_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default='{"nodes": [], "edges": []}'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('spaces', 'canvas_data')
    # ### end Alembic commands ###
