"""add_agnostic_provider_fields

Revision ID: 2a3932b10431
Revises: d79601531ec1
Create Date: 2026-03-30 23:10:04.449094

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2a3932b10431'
down_revision: Union[str, Sequence[str], None] = 'd79601531ec1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('protocol', sa.String(), nullable=True))
    op.add_column('llm_providers', sa.Column('custom_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('llm_providers', sa.Column('response_content_path', sa.String(), nullable=True))
    op.add_column('llm_providers', sa.Column('response_error_path', sa.String(), nullable=True))
    op.alter_column('llm_providers', 'auth_header_name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Authorization'::text"))
    op.alter_column('llm_providers', 'auth_header_prefix',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'Bearer '::text"))
    op.alter_column('llm_providers', 'api_key_placement',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'header'::text"))
    op.alter_column('llm_providers', 'discovery_json_path',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'data'::text"))
    op.alter_column('llm_providers', 'discovery_id_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'id'::text"))
    op.alter_column('llm_providers', 'discovery_name_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'name'::text"))
    op.alter_column('llm_providers', 'discovery_context_key',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'context_length'::text"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('llm_providers', 'discovery_context_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'context_length'::text"))
    op.alter_column('llm_providers', 'discovery_name_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'name'::text"))
    op.alter_column('llm_providers', 'discovery_id_key',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'id'::text"))
    op.alter_column('llm_providers', 'discovery_json_path',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'data'::text"))
    op.alter_column('llm_providers', 'api_key_placement',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'header'::text"))
    op.alter_column('llm_providers', 'auth_header_prefix',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Bearer '::text"))
    op.alter_column('llm_providers', 'auth_header_name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'Authorization'::text"))
    op.drop_column('llm_providers', 'response_error_path')
    op.drop_column('llm_providers', 'response_content_path')
    op.drop_column('llm_providers', 'custom_headers')
    op.drop_column('llm_providers', 'protocol')
    # ### end Alembic commands ###
