"""add_deleted_at_to_vnext_tables

Revision ID: 41eb441988ec
Revises: 601f44fa06a7
Create Date: 2026-02-18 22:14:39.024881

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '41eb441988ec'
down_revision: Union[str, Sequence[str], None] = '601f44fa06a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('crews', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('patterns', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('templates', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'deleted_at')
    op.drop_column('patterns', 'deleted_at')
    op.drop_column('crews', 'deleted_at')
    op.drop_column('agent_configs', 'deleted_at')
    # ### end Alembic commands ###
