"""add interaction mode to voice meta agent

Revision ID: 454c0a8b3f89
Revises: 93206ec8db92
Create Date: 2026-04-23 23:55:01.229222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '454c0a8b3f89'
down_revision: Union[str, Sequence[str], None] = '93206ec8db92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Manually create the enum type since interaction_mode was added as VARCHAR previously
    voice_interaction_mode = sa.Enum('STT_ONLY', 'LIVE_CONVERSATION', name='voiceinteractionmode')
    voice_interaction_mode.create(op.get_bind())

    # Need to drop default before changing type if it's incompatible
    op.execute("ALTER TABLE voice_meta_agents ALTER COLUMN interaction_mode DROP DEFAULT")
    
    # Update existing values to uppercase if they were 'Live_Conversation'
    op.execute("UPDATE voice_meta_agents SET interaction_mode = 'LIVE_CONVERSATION' WHERE interaction_mode = 'Live_Conversation'")
    op.execute("UPDATE voice_meta_agents SET interaction_mode = 'STT_ONLY' WHERE interaction_mode = 'STT_Only'")

    op.execute("ALTER TABLE voice_meta_agents ALTER COLUMN interaction_mode TYPE voiceinteractionmode USING (interaction_mode::voiceinteractionmode)")
    op.execute("ALTER TABLE voice_meta_agents ALTER COLUMN interaction_mode SET DEFAULT 'LIVE_CONVERSATION'")
    
    op.alter_column('voice_meta_agents', 'interaction_mode',
               existing_type=sa.VARCHAR(),
               type_=voice_interaction_mode,
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('voice_meta_agents', 'interaction_mode',
               existing_type=sa.Enum('STT_ONLY', 'LIVE_CONVERSATION', name='voiceinteractionmode'),
               type_=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'LIVE_CONVERSATION'::character varying"))
    
    sa.Enum(name='voiceinteractionmode').drop(op.get_bind())
    # ### end Alembic commands ###
