"""Add pricing discovery fields to LLMProvider

Revision ID: 55f7f847b6ca
Revises: f8a2b3c4d5e6
Create Date: 2026-04-01 16:57:41.253435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55f7f847b6ca'
down_revision: Union[str, Sequence[str], None] = 'f8a2b3c4d5e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('discovery_pricing_endpoint', sa.String(), nullable=True))
    op.add_column('llm_providers', sa.Column('discovery_pricing_input_key', sa.String(), nullable=True))
    op.add_column('llm_providers', sa.Column('discovery_pricing_output_key', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_providers', 'discovery_pricing_output_key')
    op.drop_column('llm_providers', 'discovery_pricing_input_key')
    op.drop_column('llm_providers', 'discovery_pricing_endpoint')
    # ### end Alembic commands ###
