"""add_vnext_agent_fields

Revision ID: 5dafe554fb60
Revises: a1b2c3d4e5f6
Create Date: 2026-03-08 18:29:41.232344

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5dafe554fb60'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_configs', sa.Column('agent_visual_url', sa.String(), nullable=True))
    op.add_column('agent_configs', sa.Column('auto_start', sa.Boolean(), nullable=True))
    op.add_column('agent_configs', sa.Column('grounded_mode', sa.Boolean(), nullable=True))
    op.add_column('agent_configs', sa.Column('native_skills', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('agent_configs', sa.Column('data_interface', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.alter_column('inbox_items', 'item_title',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('inbox_items', 'item_content',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    op.alter_column('inbox_items', 'item_source',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('inbox_items', 'item_source',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('inbox_items', 'item_content',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('inbox_items', 'item_title',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('agent_configs', 'data_interface')
    op.drop_column('agent_configs', 'native_skills')
    op.drop_column('agent_configs', 'grounded_mode')
    op.drop_column('agent_configs', 'auto_start')
    op.drop_column('agent_configs', 'agent_visual_url')
    op.drop_table('assets')
    # ### end Alembic commands ###
