"""add vector_database_config

Revision ID: 6aa628d46bea
Revises: c0a6cc333d62
Create Date: 2026-04-08 17:07:24.863444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6aa628d46bea'
down_revision: Union[str, Sequence[str], None] = 'c0a6cc333d62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vector_databases', sa.Column('vector_database_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Update VectorDBType enum with new values
    # Postgres handles ALTER TYPE ADD VALUE outside transaction blocks in some cases,
    # but here we use op.execute to safely add them.
    op.execute("ALTER TYPE vectordbtype ADD VALUE IF NOT EXISTS 'Postgres_pgvector_Local'")
    op.execute("ALTER TYPE vectordbtype ADD VALUE IF NOT EXISTS 'Supabase_pgvector_Cloud'")
    op.execute("ALTER TYPE vectordbtype ADD VALUE IF NOT EXISTS 'Qdrant_Local'")
    op.execute("ALTER TYPE vectordbtype ADD VALUE IF NOT EXISTS 'ChromaDB_Cloud'")
    op.execute("ALTER TYPE vectordbtype ADD VALUE IF NOT EXISTS 'ChromaDB_Local'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vector_databases', 'vector_database_config')
    # ### end Alembic commands ###
