"""sync_settings_crud

Revision ID: 84e1220e1e8e
Revises: 1a822cd4cf18
Create Date: 2026-03-27 18:01:48.503925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '84e1220e1e8e'
down_revision: Union[str, Sequence[str], None] = '1a822cd4cf18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_configs', 'custom_functions',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True,
               existing_server_default=sa.text("'{}'::character varying[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('agent_configs', 'custom_functions',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False,
               existing_server_default=sa.text("'{}'::character varying[]"))
    # ### end Alembic commands ###
