"""add_service_schemas

Revision ID: 8a369e2bf021
Revises: 12506e5755be
Create Date: 2026-04-17 01:20:16.210217

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8a369e2bf021'
down_revision: Union[str, Sequence[str], None] = '12506e5755be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('external_services', sa.Column('service_input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('external_services', sa.Column('service_output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_services', 'service_output_schema')
    op.drop_column('external_services', 'service_input_schema')
    # ### end Alembic commands ###
