"""migrate_voice_id_to_provider_config

Revision ID: 93206ec8db92
Revises: 7799779ca73a
Create Date: 2026-04-23 19:45:26.486271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '93206ec8db92'
down_revision: Union[str, Sequence[str], None] = '7799779ca73a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_meta_agents', sa.Column('provider_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Custom Data Migration
    op.execute("""
        UPDATE voice_meta_agents
        SET provider_config = jsonb_build_object('voice_id', voice_id)
        WHERE voice_id IS NOT NULL;
    """)

    op.drop_column('voice_meta_agents', 'voice_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voice_meta_agents', sa.Column('voice_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    
    # Custom Data Migration
    op.execute("""
        UPDATE voice_meta_agents
        SET voice_id = provider_config->>'voice_id'
        WHERE provider_config IS NOT NULL AND provider_config ? 'voice_id';
    """)
    
    # Ensure constraint after population
    op.alter_column('voice_meta_agents', 'voice_id', nullable=False)
    
    op.drop_column('voice_meta_agents', 'provider_config')
    # ### end Alembic commands ###
