"""Link automation to automation_provider

Revision ID: b163febeddc6
Revises: c94d6126435d
Create Date: 2026-04-27 21:26:00.218945

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b163febeddc6'
down_revision: Union[str, Sequence[str], None] = 'c94d6126435d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automations', sa.Column('automation_provider_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'automations', 'automation_providers', ['automation_provider_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'automations', type_='foreignkey')
    op.drop_column('automations', 'automation_provider_id')
    # ### end Alembic commands ###
