"""Add granular connection fields to vector_databases

Revision ID: c0a6cc333d62
Revises: e4b39b491241
Create Date: 2026-04-08 02:21:08.152276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0a6cc333d62'
down_revision: Union[str, Sequence[str], None] = 'e4b39b491241'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vector_databases', sa.Column('vector_database_host', sa.String(), nullable=True))
    op.add_column('vector_databases', sa.Column('vector_database_port', sa.Integer(), nullable=True))
    op.add_column('vector_databases', sa.Column('vector_database_user', sa.String(), nullable=True))
    op.add_column('vector_databases', sa.Column('vector_database_password', sa.String(), nullable=True))
    op.add_column('vector_databases', sa.Column('vector_database_db_name', sa.String(), nullable=True))
    op.add_column('vector_databases', sa.Column('vector_database_ssl_mode', sa.String(), nullable=True))
    op.add_column('vector_databases', sa.Column('vector_database_embedding_model_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vector_databases', 'embedding_models', ['vector_database_embedding_model_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vector_databases', type_='foreignkey')
    op.drop_column('vector_databases', 'vector_database_embedding_model_id')
    op.drop_column('vector_databases', 'vector_database_ssl_mode')
    op.drop_column('vector_databases', 'vector_database_db_name')
    op.drop_column('vector_databases', 'vector_database_password')
    op.drop_column('vector_databases', 'vector_database_user')
    op.drop_column('vector_databases', 'vector_database_port')
    op.drop_column('vector_databases', 'vector_database_host')
    # ### end Alembic commands ###
