"""Add pricing_sync_error column

Revision ID: c3614736c77d
Revises: d0f7a8871930
Create Date: 2026-04-01 22:33:13.316586

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3614736c77d'
down_revision: Union[str, Sequence[str], None] = 'd0f7a8871930'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('pricing_sync_error', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_providers', 'pricing_sync_error')
    # ### end Alembic commands ###
