"""Add is_available column to LLMModel

Revision ID: c8409c768bdd
Revises: c3614736c77d
Create Date: 2026-04-01 22:56:36.084202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8409c768bdd'
down_revision: Union[str, Sequence[str], None] = 'c3614736c77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_models', sa.Column('is_available', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_models', 'is_available')
    # ### end Alembic commands ###
