"""Add AutomationProvider table

Revision ID: c94d6126435d
Revises: ce62f135733a
Create Date: 2026-04-27 19:34:54.889931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c94d6126435d'
down_revision: Union[str, Sequence[str], None] = 'ce62f135733a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automation_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('platform', sa.Enum('N8N', 'ZAPIER', 'MAKE', 'CUSTOM', name='automationplatform'), nullable=False),
    sa.Column('base_url', sa.String(), nullable=True),
    sa.Column('auth_type', sa.Enum('HEADER', 'BEARER', 'NONE', name='automationauthtype'), nullable=False),
    sa.Column('auth_header_name', sa.String(), nullable=True),
    sa.Column('auth_secret', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('automation_providers')
    # ### end Alembic commands ###
