"""Add pricing scraper columns

Revision ID: d0f7a8871930
Revises: 55f7f847b6ca
Create Date: 2026-04-01 18:13:09.535840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd0f7a8871930'
down_revision: Union[str, Sequence[str], None] = '55f7f847b6ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_providers', sa.Column('pricing_page_url', sa.String(), nullable=True))
    op.add_column('llm_providers', sa.Column('pricing_scraper_strategy', sa.String(), nullable=True))
    op.add_column('llm_providers', sa.Column('pricing_last_synced_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('llm_providers', sa.Column('pricing_data_cache', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_providers', 'pricing_data_cache')
    op.drop_column('llm_providers', 'pricing_last_synced_at')
    op.drop_column('llm_providers', 'pricing_scraper_strategy')
    op.drop_column('llm_providers', 'pricing_page_url')
    # ### end Alembic commands ###
