"""update_llm_provider_schema

Revision ID: d2f9af0c65be
Revises: 045969777155
Create Date: 2026-03-30 01:10:49.904310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd2f9af0c65be'
down_revision: Union[str, Sequence[str], None] = '045969777155'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Create Enum type manually for PostgreSQL
    provider_type_enum = sa.Enum('cloud', 'meta', 'local', name='providertype')
    provider_type_enum.create(op.get_bind(), checkfirst=True)

    # Add columns as nullable first
    op.add_column('llm_providers', sa.Column('provider_technical_id', sa.String(), nullable=True))
    op.add_column('llm_providers', sa.Column('provider_type', provider_type_enum, nullable=True))
    op.add_column('llm_providers', sa.Column('provider_api_key', sa.String(), nullable=True))
    op.add_column('llm_providers', sa.Column('provider_custom_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    
    # Update existing rows
    op.execute("UPDATE llm_providers SET provider_technical_id = LOWER(REPLACE(provider_name, ' ', '_')), provider_type = 'cloud'")
    
    # Make columns NOT NULL
    op.alter_column('llm_providers', 'provider_technical_id', nullable=False)
    op.alter_column('llm_providers', 'provider_type', nullable=False)
    
    op.create_unique_constraint(None, 'llm_providers', ['provider_technical_id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'llm_providers', type_='unique')
    op.drop_column('llm_providers', 'provider_custom_config')
    op.drop_column('llm_providers', 'provider_api_key')
    op.drop_column('llm_providers', 'provider_type')
    op.drop_column('llm_providers', 'provider_technical_id')
    # ### end Alembic commands ###
