"""add_reasoning_and_prompt_to_models

Revision ID: d79601531ec1
Revises: d2f9af0c65be
Create Date: 2026-03-30 13:38:36.374512

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd79601531ec1'
down_revision: Union[str, Sequence[str], None] = 'd2f9af0c65be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('llm_models', sa.Column('model_reasoning_effort', sa.String(), nullable=True))
    op.add_column('llm_models', sa.Column('model_system_prompt', sa.String(), nullable=True))
    op.add_column('llm_models', sa.Column('model_custom_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('llm_models', 'model_custom_params')
    op.drop_column('llm_models', 'model_system_prompt')
    op.drop_column('llm_models', 'model_reasoning_effort')
    # ### end Alembic commands ###
