"""init_schema_indexes_logs

Revision ID: da0ef98d7a99
Revises: 
Create Date: 2025-12-16 01:14:21.825386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = 'da0ef98d7a99'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('agent_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('MANAGER', 'RESEARCHER', 'BUILDER', 'WRITER', name='agentrole'), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('model_tier', sa.Enum('TIER_1_FAST', 'TIER_2_EXPERT', name='modeltier'), nullable=False),
    sa.Column('tools', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('system_instruction', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role')
    )
    op.create_unique_constraint(None, 'agent_configs', ['role'])
    # assets table removed here, created in d603bce469d5
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('domain', sa.Enum('PRODUCT', 'DISCOVERY', 'DESIGN', 'DELIVERY', 'GROWTH', 'WRITING', name='hubtype'), nullable=False),
    sa.Column('status', sa.Enum('IDEA', 'IN_PROGRESS', 'REVIEW', 'DONE', 'ARCHIVED', name='status'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artifacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('MARKDOWN', 'CODE', 'JSON', 'IMAGE', name='filetype'), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'REVIEWED', 'APPROVED', name='reviewstate'), nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_artifacts_metadata', 'artifacts', ['metadata'], unique=False, postgresql_using='gin')
    op.create_table('chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('agent_role', sa.Enum('MANAGER', 'RESEARCHER', 'BUILDER', 'WRITER', name='agentrole'), nullable=False),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_chats_history', 'chat_sessions', ['history'], unique=False, postgresql_using='gin')
    op.create_table('agent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('agent_role', sa.Enum('MANAGER', 'RESEARCHER', 'BUILDER', 'WRITER', name='agentrole'), nullable=False),
    sa.Column('level', sa.String(), nullable=False),
    sa.Column('event', sa.String(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_agent_logs_content', 'agent_logs', ['content'], unique=False, postgresql_using='gin')
    op.create_index('idx_agent_logs_session', 'agent_logs', ['session_id'], unique=False)
    # op.drop_table('axon-table')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('axon-table',
    sa.Column('id', sa.BIGINT(), sa.Identity(always=False, start=1, increment=1, minvalue=1, maxvalue=9223372036854775807, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('axon-table_pkey'))
    )
    op.drop_index('idx_agent_logs_session', table_name='agent_logs')
    op.drop_index('idx_agent_logs_content', table_name='agent_logs', postgresql_using='gin')
    op.drop_table('agent_logs')
    op.drop_index('idx_chats_history', table_name='chat_sessions', postgresql_using='gin')
    op.drop_table('chat_sessions')
    op.drop_index('idx_artifacts_metadata', table_name='artifacts', postgresql_using='gin')
    op.drop_table('artifacts')
    op.drop_table('projects')
    op.drop_index(op.f('ix_assets_slug'), table_name='assets')
    op.drop_index('idx_assets_metadata', table_name='assets', postgresql_using='gin')
    op.drop_index('idx_assets_embedding', table_name='assets', postgresql_using='hnsw', postgresql_ops={'description_embedding': 'vector_cosine_ops'})
    op.drop_table('assets')
    op.drop_table('agent_configs')
    # ### end Alembic commands ###
