"""Add missing fields to AgentConfig

Revision ID: e743c61acaa7
Revises: 5dafe554fb60
Create Date: 2026-03-13 18:30:36.003947

"""
from typing import Sequence, Union



# revision identifiers, used by Alembic.
revision: str = 'e743c61acaa7'
down_revision: Union[str, Sequence[str], None] = '5dafe554fb60'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
