"""add_space_ids_to_projects

Revision ID: f2e43187e1b5
Revises: 8a369e2bf021
Create Date: 2026-04-18 22:37:35.808651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f2e43187e1b5'
down_revision: Union[str, Sequence[str], None] = '8a369e2bf021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('space_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.drop_constraint(op.f('projects_space_id_fkey'), 'projects', type_='foreignkey')
    op.drop_column('projects', 'space_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('space_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('projects_space_id_fkey'), 'projects', 'spaces', ['space_id'], ['id'])
    op.drop_column('projects', 'space_ids')
    # ### end Alembic commands ###
