import { InboxList } from "@/modules/inbox/features/review-inbox/ui/inbox-list";
import { getInboxItems } from "@/modules/inbox/features/review-inbox/infrastructure/api";

const InboxPage = async () => {
    const items = await getInboxItems();

    return (
        <div className="container mx-auto py-10 px-4">
            <header className="mb-8">
                <h1 className="text-3xl font-bold tracking-tight">Inbox</h1>
                <p className="text-muted-foreground mt-2">
                    Review and approve content generated by your agents.
                </p>
            </header>

            <main>
                <InboxList items={items} />
            </main>
        </div>
    );
};

export default InboxPage;