import { InboxList } from "@/modules/inbox/components/inbox-list";

const InboxPage = () => {
    return (
        <div className="container mx-auto py-10 px-4">
            <header className="mb-8">
                <h1 className="text-3xl font-bold tracking-tight">Inbox</h1>
                <p className="text-muted-foreground mt-2">
                    Review and approve content generated by your agents.
                </p>
            </header>

            <main>
                <InboxList />
            </main>
        </div>
    );
};

export default InboxPage;