"""add_spaces_tables

Revision ID: 04e09cf04e85
Revises: d603bce469d5
Create Date: 2026-02-17 21:58:45.364268

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04e09cf04e85'
down_revision: Union[str, Sequence[str], None] = 'd603bce469d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_name', sa.String(), nullable=False),
    sa.Column('space_description', sa.String(), nullable=True),
    sa.Column('space_status', sa.Enum('DRAFT', 'LINKED', name='spacestatus'), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('space_viewport_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_nodes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('node_label', sa.String(), nullable=True),
    sa.Column('node_position_x', sa.Float(), nullable=False),
    sa.Column('node_position_y', sa.Float(), nullable=False),
    sa.Column('node_execution_status', sa.Enum('IDLE', 'MISSING_CONTEXT', 'WORKING', 'BRIEFING', 'CONSULTATION', 'DONE', 'ERROR', name='nodeexecutionstatus'), nullable=False),
    sa.Column('node_runtime_state', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('component_type', sa.String(), nullable=False),
    sa.Column('component_id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('space_zones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('workspace_domain', sa.Enum('DISCOVERY', 'DESIGN', 'DELIVERY', 'GROWTH', name='workspacedomain'), nullable=False),
    sa.Column('zone_position_x', sa.Float(), nullable=False),
    sa.Column('zone_position_y', sa.Float(), nullable=False),
    sa.Column('zone_width', sa.Float(), nullable=False),
    sa.Column('zone_height', sa.Float(), nullable=False),
    sa.Column('zone_color', sa.String(), nullable=True),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('canvas_chat_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('messages', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('session_status', sa.Enum('ACTIVE', 'RESOLVED', name='sessionstatus'), nullable=False),
    sa.Column('canvas_node_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canvas_node_id'], ['space_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('log_status', sa.Enum('RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='logstatus'), nullable=False),
    sa.Column('log_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('log_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('log_outcome', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('log_streaming', sa.Text(), nullable=True),
    sa.Column('log_error_message', sa.String(), nullable=True),
    sa.Column('log_token_consumed', sa.Integer(), nullable=True),
    sa.Column('log_execution_cost', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('canvas_node_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['canvas_node_id'], ['space_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('node_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_source_handle_id', sa.String(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('edge_target_handle_id', sa.String(), nullable=False),
    sa.Column('space_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['space_nodes.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['spaces.id'], ),
    sa.ForeignKeyConstraint(['target_node_id'], ['space_nodes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('node_edges')
    op.drop_table('execution_logs')
    op.drop_table('canvas_chat_sessions')
    op.drop_table('space_zones')
    op.drop_table('space_nodes')
    op.drop_table('spaces')
    # ### end Alembic commands ###
