"""add_deleted_at_to_workspace_tables

Revision ID: 0d03792a31f3
Revises: cba1c5362b01
Create Date: 2026-03-17 19:04:51.367251

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d03792a31f3'
down_revision: Union[str, Sequence[str], None] = 'cba1c5362b01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('automations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('external_services', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('external_services', 'deleted_at')
    op.drop_column('automations', 'deleted_at')
    # ### end Alembic commands ###
