"""make_scenario_project_id_nullable

Revision ID: 473a652c2712
Revises: c666a116d70b
Create Date: 2025-12-16 23:11:44.156453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '473a652c2712'
down_revision: Union[str, Sequence[str], None] = 'c666a116d70b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenarios', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scenarios', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
