"""gate_0_vnext_schema

Revision ID: 5f0314dd3c96
Revises: 6b293c067de9
Create Date: 2026-02-18 20:47:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = '5f0314dd3c96'
down_revision: Union[str, Sequence[str], None] = '6b293c067de9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('automations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('automation_name', sa.String(), nullable=False),
    sa.Column('automation_description', sa.String(), nullable=True),
    sa.Column('automation_platform', sa.Enum('N8N', 'ZAPIER', 'MAKE', 'CUSTOM', name='automationplatform'), nullable=False),
    sa.Column('automation_webhook_url', sa.String(), nullable=False),
    sa.Column('automation_http_method', sa.Enum('POST', 'GET', 'PUT', name='automationhttpmethod'), nullable=False),
    sa.Column('automation_auth_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('automation_input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('automation_output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('automation_validation_status', sa.Enum('VALID', 'INVALID', 'UNTESTED', name='validationstatus'), nullable=False),
    sa.Column('automation_last_validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('automation_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('availability_workspace', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chunking_strategies',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('strategy_name', sa.String(), nullable=False),
    sa.Column('strategy_chunking_method', sa.Enum('RECURSIVE_CHARACTER', 'CODE_SPLITTER', 'TOKEN_SPLITTER', name='chunkingmethod'), nullable=False),
    sa.Column('strategy_chunk_size', sa.Integer(), nullable=False),
    sa.Column('strategy_chunk_overlap', sa.Integer(), nullable=False),
    sa.Column('strategy_chunk_boundaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('embedding_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_provider_name', sa.String(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_vector_dimensions', sa.Integer(), nullable=False),
    sa.Column('model_max_context_tokens', sa.Integer(), nullable=False),
    sa.Column('model_cost_per_1m_tokens', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('external_services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_name', sa.String(), nullable=False),
    sa.Column('service_category', sa.Enum('UTILITY', 'GENAI', 'SCRAPING', 'BUSINESS', name='servicecategory'), nullable=False),
    sa.Column('service_url', sa.String(), nullable=False),
    sa.Column('service_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('availability_workspace', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('internal_tools',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tool_function_name', sa.String(), nullable=False),
    sa.Column('tool_display_name', sa.String(), nullable=False),
    sa.Column('tool_description', sa.String(), nullable=False),
    sa.Column('tool_category', sa.Enum('PRIMEVAL', 'AI_UTILS', 'LOCAL', 'OTHER', name='toolcategory'), nullable=False),
    sa.Column('tool_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('tool_input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('tool_is_active', sa.Boolean(), nullable=False),
    sa.Column('availability_workspace', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tool_function_name')
    )
    op.create_table('knowledge_hubs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hub_name', sa.String(), nullable=False),
    sa.Column('hub_description', sa.String(), nullable=True),
    sa.Column('workspace_domain', sa.String(), nullable=False),
    sa.Column('hub_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hub_name')
    )
    op.create_table('llm_providers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('provider_name', sa.String(), nullable=False),
    sa.Column('provider_api_key_required', sa.Boolean(), nullable=True),
    sa.Column('provider_api_endpoint', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_name')
    )
    op.create_table('patterns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pattern_name', sa.String(), nullable=False),
    sa.Column('pattern_type', sa.Enum('PATTERN', 'REUSABLE_TEMPLATE', name='patterntype'), nullable=True),
    sa.Column('pattern_okr_context', sa.String(), nullable=True),
    sa.Column('pattern_graph_structure', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pattern_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('availability_workspace', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('prompt_archetypes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('archetype_name', sa.String(), nullable=False),
    sa.Column('archetype_description', sa.String(), nullable=True),
    sa.Column('archetype_role', sa.String(), nullable=False),
    sa.Column('archetype_goal', sa.String(), nullable=False),
    sa.Column('archetype_backstory', sa.String(), nullable=False),
    sa.Column('archetype_guardrails', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('archetype_knowledge_hubs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('archetype_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('workspace_domain', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('archetype_name')
    )
    op.create_table('templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('template_name', sa.String(), nullable=False),
    sa.Column('template_description', sa.String(), nullable=True),
    sa.Column('template_markdown_content', sa.String(), nullable=False),
    sa.Column('template_checklist_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('template_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('availability_workspace', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_email', sa.String(), nullable=False),
    sa.Column('user_email_verified', sa.Boolean(), nullable=True),
    sa.Column('user_display_name', sa.String(), nullable=False),
    sa.Column('user_avatar_url', sa.String(), nullable=True),
    sa.Column('user_password_hash', sa.String(), nullable=False),
    sa.Column('user_preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_role', sa.Enum('ADMIN', 'WORKER', name='userrole'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    op.create_table('vector_databases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vector_database_name', sa.String(), nullable=False),
    sa.Column('vector_database_type', sa.Enum('POSTGRES_PGVECTOR', 'CHROMADB', 'PINECONE', name='vectordbtype'), nullable=False),
    sa.Column('vector_database_connection_url', sa.String(), nullable=True),
    sa.Column('vector_database_connection_string', sa.String(), nullable=True),
    sa.Column('vector_database_index_method', sa.Enum('HNSW', 'IVFFLAT', name='indexmethod'), nullable=True),
    sa.Column('vector_database_connection_status', sa.Enum('CONNECTED', 'DISCONNECTED', name='connectionstatus'), nullable=True),
    sa.Column('vector_database_collection_name', sa.String(), nullable=False),
    sa.Column('vector_database_embedding_model_reference', sa.String(), nullable=False),
    sa.Column('vector_database_total_vectors', sa.Integer(), nullable=True),
    sa.Column('vector_database_size', sa.Integer(), nullable=True),
    sa.Column('vector_database_expected_dimensions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voice_meta_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('voice_provider', sa.Enum('ELEVENLABS', 'AZURE_TTS', 'GOOGLE_TTS', name='voiceprovider'), nullable=False),
    sa.Column('voice_id', sa.String(), nullable=False),
    sa.Column('meta_agent_system_prompt', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('automation_executions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('automation_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['automation_id'], ['automations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('knowledge_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file_name', sa.String(), nullable=False),
    sa.Column('source_file_format', sa.Enum('PDF', 'MD', 'TXT', 'DOCX', 'URL', name='sourcefileformat'), nullable=False),
    sa.Column('source_file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('source_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_rag_indexing_status', sa.Enum('PENDING', 'INDEXING', 'READY', 'ERROR', name='ragindexingstatus'), nullable=False),
    sa.Column('source_indexed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_chunk_count', sa.Integer(), nullable=True),
    sa.Column('source_chunking_strategy_ref', sa.String(), nullable=True),
    sa.Column('source_indexing_error', sa.String(), nullable=True),
    sa.Column('knowledge_hub_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_hub_id'], ['knowledge_hubs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.String(), nullable=False),
    sa.Column('model_display_name', sa.String(), nullable=False),
    sa.Column('model_tier', sa.Enum('TIER1', 'TIER2', name='llm_model_tier'), nullable=True),
    sa.Column('model_capabilities_flags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('model_context_window', sa.Integer(), nullable=True),
    sa.Column('model_supports_thinking', sa.Boolean(), nullable=True),
    sa.Column('model_pricing_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_provider_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['llm_provider_id'], ['llm_providers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service_capabilities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('capability_name', sa.String(), nullable=False),
    sa.Column('capability_description', sa.String(), nullable=True),
    sa.Column('external_service_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['external_service_id'], ['external_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('llm_routers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('router_alias', sa.String(), nullable=False),
    sa.Column('router_strategy', sa.Enum('COST_OPTIMIZED', 'SPEED_OPTIMIZED', 'QUALITY_OPTIMIZED', name='routerstrategy'), nullable=True),
    sa.Column('router_max_tokens_threshold', sa.Integer(), nullable=True),
    sa.Column('router_cost_limit_per_request', sa.Float(), nullable=True),
    sa.Column('primary_model_id', sa.UUID(), nullable=False),
    sa.Column('fallback_model_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['fallback_model_id'], ['llm_models.id'], ),
    sa.ForeignKeyConstraint(['primary_model_id'], ['llm_models.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('router_alias')
    )
    op.create_table('meta_agents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('meta_agent_system_prompt', sa.String(), nullable=False),
    sa.Column('meta_agent_temperature', sa.Float(), nullable=True),
    sa.Column('meta_agent_rag_enabled', sa.Boolean(), nullable=True),
    sa.Column('meta_agent_system_knowledge_rags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('llm_model_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['llm_model_id'], ['llm_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text_chunks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('chunk_text', sa.String(), nullable=False),
    sa.Column('chunk_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('chunk_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('chunk_token_count', sa.Integer(), nullable=True),
    sa.Column('knowledge_source_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['knowledge_source_id'], ['knowledge_sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('crew_name', sa.String(), nullable=False),
    sa.Column('crew_description', sa.String(), nullable=True),
    sa.Column('crew_process_type', sa.Enum('SEQUENTIAL', 'HIERARCHICAL', 'PARALLEL', name='processtype'), nullable=True),
    sa.Column('manager_agent_id', sa.UUID(), nullable=True),
    sa.Column('crew_keywords', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('availability_workspace', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['manager_agent_id'], ['agent_configs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('crew_agents',
    sa.Column('crew_id', sa.UUID(), nullable=False),
    sa.Column('agent_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent_configs.id'], ),
    sa.ForeignKeyConstraint(['crew_id'], ['crews.id'], ),
    sa.PrimaryKeyConstraint('crew_id', 'agent_id')
    )
    op.drop_index(op.f('idx_assets_embedding'), table_name='assets', postgresql_ops={'description_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_index(op.f('idx_assets_metadata'), table_name='assets', postgresql_using='gin')
    op.drop_index(op.f('ix_assets_slug'), table_name='assets')
    op.drop_table('assets')
    op.add_column('agent_configs', sa.Column('agent_name', sa.String(), nullable=True))
    op.add_column('agent_configs', sa.Column('agent_role_text', sa.String(), nullable=True))
    op.add_column('agent_configs', sa.Column('agent_goal', sa.String(), nullable=True))
    op.add_column('agent_configs', sa.Column('agent_backstory', sa.String(), nullable=True))
    op.add_column('agent_configs', sa.Column('guardrails', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_configs', sa.Column('few_shot_examples', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_configs', sa.Column('reflexion', sa.Boolean(), nullable=True))
    op.add_column('agent_configs', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('agent_configs', sa.Column('rag_enforcement', sa.Boolean(), nullable=True))
    op.add_column('agent_configs', sa.Column('input_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_configs', sa.Column('output_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('agent_configs', sa.Column('availability_workspace', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('agent_configs', sa.Column('agent_keywords', postgresql.ARRAY(sa.String()), nullable=True))
    op.add_column('agent_configs', sa.Column('llm_model_id', sa.UUID(), nullable=True))
    op.add_column('agent_configs', sa.Column('knowledge_hub_ids', postgresql.ARRAY(sa.UUID()), nullable=True))
    op.alter_column('agent_configs', 'role',
               existing_type=postgresql.ENUM('MANAGER', 'RESEARCHER', 'BUILDER', 'WRITER', name='agentrole'),
               nullable=True)
    op.alter_column('agent_configs', 'model_tier',
               existing_type=postgresql.ENUM('TIER_1_FAST', 'TIER_2_EXPERT', name='modeltier'),
               nullable=True)
    op.create_foreign_key(None, 'agent_configs', 'llm_models', ['llm_model_id'], ['id'])
    op.alter_column('agent_logs', 'agent_role',
               existing_type=postgresql.ENUM('MANAGER', 'RESEARCHER', 'BUILDER', 'WRITER', name='agentrole'),
               nullable=True)
    op.alter_column('chat_sessions', 'agent_role',
               existing_type=postgresql.ENUM('MANAGER', 'RESEARCHER', 'BUILDER', 'WRITER', name='agentrole'),
               nullable=True)
    op.add_column('inbox_items', sa.Column('artifact_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'inbox_items', 'project_artifacts', ['artifact_id'], ['id'])
    op.drop_column('inbox_items', 'artifact_source_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('inbox_items', sa.Column('artifact_source_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'inbox_items', type_='foreignkey')
    op.drop_column('inbox_items', 'artifact_id')
    op.alter_column('chat_sessions', 'agent_role',
               existing_type=postgresql.ENUM('MANAGER', 'RESEARCHER', 'BUILDER', 'WRITER', name='agentrole'),
               nullable=False)
    op.alter_column('agent_logs', 'agent_role',
               existing_type=postgresql.ENUM('MANAGER', 'RESEARCHER', 'BUILDER', 'WRITER', name='agentrole'),
               nullable=False)
    op.drop_constraint(None, 'agent_configs', type_='foreignkey')
    op.alter_column('agent_configs', 'model_tier',
               existing_type=postgresql.ENUM('TIER_1_FAST', 'TIER_2_EXPERT', name='modeltier'),
               nullable=False)
    op.alter_column('agent_configs', 'role',
               existing_type=postgresql.ENUM('MANAGER', 'RESEARCHER', 'BUILDER', 'WRITER', name='agentrole'),
               nullable=False)
    op.drop_column('agent_configs', 'knowledge_hub_ids')
    op.drop_column('agent_configs', 'llm_model_id')
    op.drop_column('agent_configs', 'agent_keywords')
    op.drop_column('agent_configs', 'availability_workspace')
    op.drop_column('agent_configs', 'output_schema')
    op.drop_column('agent_configs', 'input_schema')
    op.drop_column('agent_configs', 'rag_enforcement')
    op.drop_column('agent_configs', 'temperature')
    op.drop_column('agent_configs', 'reflexion')
    op.drop_column('agent_configs', 'few_shot_examples')
    op.drop_column('agent_configs', 'guardrails')
    op.drop_column('agent_configs', 'agent_backstory')
    op.drop_column('agent_configs', 'agent_goal')
    op.drop_column('agent_configs', 'agent_role_text')
    op.drop_column('agent_configs', 'agent_name')
    op.create_table('assets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('domain', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('description_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('assets_pkey'))
    )
    op.create_index(op.f('ix_assets_slug'), 'assets', ['slug'], unique=True)
    op.create_index(op.f('idx_assets_metadata'), 'assets', ['metadata'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_assets_embedding'), 'assets', ['description_embedding'], unique=False, postgresql_ops={'description_embedding': 'vector_cosine_ops'}, postgresql_using='hnsw')
    op.drop_table('crew_agents')
    op.drop_table('crews')
    op.drop_table('text_chunks')
    op.drop_table('meta_agents')
    op.drop_table('llm_routers')
    op.drop_table('service_capabilities')
    op.drop_table('llm_models')
    op.drop_table('knowledge_sources')
    op.drop_table('automation_executions')
    op.drop_table('voice_meta_agents')
    op.drop_table('vector_databases')
    op.drop_table('users')
    op.drop_table('templates')
    op.drop_table('prompt_archetypes')
    op.drop_table('patterns')
    op.drop_table('llm_providers')
    op.drop_table('knowledge_hubs')
    op.drop_table('internal_tools')
    op.drop_table('external_services')
    op.drop_table('embedding_models')
    op.drop_table('chunking_strategies')
    op.drop_table('automations')
    # ### end Alembic commands ###
