"""add_assets_table

Revision ID: d603bce469d5
Revises: 473a652c2712
Create Date: 2025-12-17 00:41:37.951986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'd603bce469d5'
down_revision: Union[str, Sequence[str], None] = '473a652c2712'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        'assets',
        sa.Column('id', sa.UUID(), primary_key=True),
        sa.Column('slug', sa.String(), unique=True, nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('content', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('domain', sa.String(), nullable=False),
        sa.Column('metadata', sa.JSON(), default={}),
        sa.Column('description_embedding', pgvector.sqlalchemy.Vector(768), nullable=True),
        sa.Column('is_deleted', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(timezone=True), default=sa.func.now()),
        sa.Column('updated_at', sa.DateTime(timezone=True), default=sa.func.now(), onupdate=sa.func.now()),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
